config/routes.rb
LeagueApp::Application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  resources :sessions
  resources :leagues do
    get 'allLeagues', on: :collection
  end
  resources :days
  resources :games
  resources :teams do
    get 'allTeams', on: :collection
  end
  resources :users
  resources :stats
  resources :teams
  resources :players do
    get 'teamPlayers', on: :collection
  end
  resources :league_teams 
  resources :team_leagues, only: :index
  
  root 'users#new'

end

app/models/league.rb
class League < ActiveRecord::Base
  belongs_to :user
  has_many :days
  has_many :games
  has_many :league_teams
  has_many :teams, through: :league_teams

  validates :name, :start_date, :end_date, presence: true
  validates_uniqueness_of :name, message: " taken please choose another name"
  before_destroy :destroy_children

  def destroy_children
  	Day.where(league_id: self.id).destroy_all
    Game.where(league_id: self.id).destroy_all
    LeagueTeam.where(league_id: self.id).destroy_all
  end
  
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:index, :new, :edit, :create, :update, :delete]
  respond_to :html, :json

  def allLeagues
    @leagues = League.all
    respond_with @leagues
  end

  # GET /leagues
  def index
    @leagues = current_user.leagues if current_user && current_user.user_type == 'league_admin'
    @leagues = Team.where(id: params[:team_id])[0].leagues if params[:team_id]
    respond_with @leagues
  end

  # GET /leagues/1
  def show
    @days = @league.days
    respond_with @league
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues
  def create
    @league = League.new(league_params)
    @league.user = current_user

    if @league.save
      @first = @league.start_date
      @last = @league.end_date
      create_days(@league, @first, @last)
      redirect_to leagues_path, notice: 'League was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /leagues/1
  def update
    if @league.update(league_params)
      redirect_to @league, notice: 'League was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /leagues/1
  def destroy
    @league.destroy
    redirect_to leagues_url, notice: 'League was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def league_params
      params.require(:league).permit(:name, :start_date, :end_date, :description, :user_id, :locations, :sport)
    end
end

app/views/leagues/_form.html.erb
<%= form_for(@league) do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.text_field :name, placeholder: 'Unique League Name' %>
    <%= f.date_field :start_date, placeholder: Date.today %>
    <%= f.date_field :end_date, placeholder: Date.today %>
    <%= f.text_field :description, placeholder: 'League Description (optional)'%>
    <%= f.submit %>
  </div>
<% end %>

app/views/leagues/edit.html.erb
<div id="edit_league_modal">
	<div class="modal-header">
	    <%if !@league.errors.any? %><button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button><% end %>
	    <h4 class="modal-title" id="myModalLabel">( Edit League ) <small> Update the Name, Dates and Locations of your new League</small></h4>
	</div>
	<div class="modal-body">

		 <% if @league.errors.any? %>
	    <ul class="list-group">
	      <% @league.errors.full_messages.each do |message| %>
	        <li class="list-group-item list-group-item-danger col-sm-offset-1"><%= message %></li>
	      <% end %>
	    </ul>
  	<% end %>
		
		<%= form_for @league, :html => {:class => 'form-horizontal', :role => 'form'} do |l| %>
			<div class='form-group'>
				<label for="league-name" class='col-sm-3 control-label'>Name</label>
				<div class='col-sm-9'>
					<%= l.text_field :name, :class => 'form-control', :id => 'league-name', :placeholder => 'Please create a unique name' %>
				</div>
			</div>
			<div class='form-group'>
				<label for="league-start" class='col-sm-3 control-label'>Start Date</label>
				<div class='col-sm-9'>
					<%= l.date_field :start_date, :class => 'form-control', :id => 'league-start'%>
				</div>
			</div>
			<div class='form-group'>
				<label for="league-end" class='col-sm-3 control-label'>End Date</label>
				<div class='col-sm-9'>
					<%= l.date_field :end_date, :class => 'form-control', :id => 'league-end'%>
				</div>
			</div>
			<div class='form-group'>
				<label for="league-locations" class='col-sm-3 control-label'>Locations</label>
				<div class='col-sm-9'>
					<%= l.text_field :locations, :class => 'form-control', :id => 'league-locations', :placeholder => 'Locations' %>
				</div>
			</div>
			<div class='form-group'>
				<label for="league-sport" class='col-sm-3 control-label'>Sport</label>
				<div class='col-sm-9'>
					<%= l.select :sport, 
					[
						['Basketball','Basketball'],
						['Football', 'Football'],
						['Softball','Softball']
					], :class => 'form-control', :id => 'league-sport', :placeholder => 'Basketball or Football' %>
				</div>
			</div>
			<div class='form-group'>
				<label for="league-description" class='col-sm-3 control-label'>Description</label>
				<div class='col-sm-9'>
					<%= l.text_field :description, :class => 'form-control', :id => 'league-description', :placeholder => 'Description (optional)' %>
				</div>
			</div>
			<div class='form-group'>
				<div class="col-sm-offset-3 col-sm-9">
					<% if @league.errors.any? %>
						<%= l.submit "Submit", :class => 'btn btn-info', style: 'width:20%' %>
						<%= link_to "Back", leagues_path, :class => 'btn btn-default', style: 'width:20%'  %>
					<% else %>
						<%= l.submit "Submit", :class => 'btn btn-info', style: 'width:20%'  %>
						<button type="button" class="btn btn-default" style="width:20%" data-dismiss="modal">Close</button>
					<% end %>
				</div>
			</div>
		<% end %>
		
	</div>
</div>


	  

app/views/leagues/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3"></div>

    <div class="col-sm-6">
      <center>
        <h1>Your Leagues</h1>
        <div class="panel-group" id="accordion" style="margin:0px;">
          <% League.where(:user_id => current_user.id).sort{|dt| dt.start_date}.reverse.each do |l| %>
          <div class="panel panel-default" style="margin:0px;">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#<%=l.id%>">
                  <h4><%= l.name %> <small><%=l.sport%></small></h4>
                </a>
              </h4>
            </div>
            <div id="<%=l.id%>" class="panel-collapse collapse out">
              <div class="panel-body">
                <div><i>Start Date:</i> <strong><%= l.start_date.strftime("%A, %b %d %Y") %></strong></div>
                <div><i>End Date:</i> <strong><%= l.end_date.strftime("%A, %b %d %Y") %></strong></div>
                <div><i>Locations:</i> <strong><%= l.locations %></strong></div>
                <div><i>Description:</i> <strong><%= l.description %></strong></div>
                <hr>
                <%= link_to "View", league_path(l), class: 'btn btn-info', id: 'leagueList' %>
                <div class="btn btn-warning" data-toggle="modal" data-target="#editModal" data-remote="<%= edit_league_path(l.id) %> #edit_league_modal">Edit</div>
                <%= link_to "Delete", l, method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure you want to delete #{l.name}"}%>
              </div>
            </div>
          </div>
          <% end %>
        </div>

        <button data-toggle="modal" data-target="#leagueModal" data-remote="<%= new_league_path %> #new_league_modal" class="btn btn-default btn-block">+ League</button><br>
        <br>
      </center>

      <%= link_to "Logout ", session_path(session), method: :delete %>

      <div class="modal fade" id="leagueModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
          </div>
        </div>
      </div>
      <div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/leagues/new.html.erb
<div id="new_league_modal">
	<div class="modal-header">
	    <%if !@league.errors.any? %><button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button><% end %>
	    <h4 class="modal-title" id="myModalLabel">( New League ) <small> Set the Name, Dates and Locations of your new League</small></h4>
	</div>
	<div class="modal-body">

		 <% if @league.errors.any? %>
	    <ul class="list-group">
	      <% @league.errors.full_messages.each do |message| %>
	        <li class="list-group-item list-group-item-danger col-sm-offset-1"><%= message %></li>
	      <% end %>
	    </ul>
  	<% end %>
		
		<%= form_for @league, :html => {:class => 'form-horizontal', :role => 'form'} do |l| %>
			<div class='form-group'>
				<label for="league-name" class='col-sm-3 control-label'>Name</label>
				<div class='col-sm-9'>
					<%= l.text_field :name, :class => 'form-control', :id => 'league-name', :placeholder => 'Please create a unique name' %>
				</div>
			</div>
			<div class='form-group'>
				<label for="league-start" class='col-sm-3 control-label'>Start Date</label>
				<div class='col-sm-9'>
					<%= l.date_field :start_date, :class => 'form-control', :id => 'league-start'%>
				</div>
			</div>
			<div class='form-group'>
				<label for="league-end" class='col-sm-3 control-label'>End Date</label>
				<div class='col-sm-9'>
					<%= l.date_field :end_date, :class => 'form-control', :id => 'league-end'%>
				</div>
			</div>
			<div class='form-group'>
				<label for="league-locations" class='col-sm-3 control-label'>Locations</label>
				<div class='col-sm-9'>
					<%= l.text_field :locations, :class => 'form-control', :id => 'league-locations', :placeholder => 'Locations' %>
				</div>
			</div>
			<div class='form-group'>
				<label for="league-sport" class='col-sm-3 control-label'>Sport</label>
				<div class='col-sm-9'>
					<%= l.select :sport, 
					[
						['Basketball','Basketball'],
						['Football', 'Football'],
						['Softball','Softball']
					], :class => 'form-control', :id => 'league-sport', :placeholder => 'Basketball or Football' %>
				</div>
			</div>
			<div class='form-group'>
				<label for="league-description" class='col-sm-3 control-label'>Description</label>
				<div class='col-sm-9'>
					<%= l.text_field :description, :class => 'form-control', :id => 'league-description', :placeholder => 'Description (optional)' %>
				</div>
			</div>
			<div class='form-group'>
				<div class="col-sm-offset-3 col-sm-9">
					<% if @league.errors.any? %>
						<%= l.submit "Submit", :class => 'btn btn-info' %>
						<%= link_to "Back", leagues_path, :class => 'btn btn-default' %>
					<% else %>
						<%= l.submit "Submit", :class => 'btn btn-info' %>
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<% end %>
				</div>
			</div>
		<% end %>
		
	</div>
</div>


	  

app/views/leagues/show.html.erb
<div class="container-fluid" x-ng-app="leagueapp" style="margin-top:60px">

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation" id="navBar">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/leagues/<%=@league.id%>">( RecStar ) <small><%= @league.name%></small></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a data-toggle="dropdown">League Menu<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
              <li>
                <a ui-sref="league">Schedule and Standings</a>
              </li>
              <li>
                <a ui-sref="results">Results and Stats</a>
              </li>
              <% if current_user && current_user.user_type == 'team_owner' %>
              <li>
                <a href="/teams/<%=current_user.teams[0].id%>">My Team</a>
              </li>
              <% elsif current_user && current_user.user_type == 'league_admin' %>
              <li role="presentation" class="divider"></li>
              <li>
                <a href="/leagues">My Leagues</a>
              </li>
              <%end%>
            </ul>
          </li>
          <% if current_user %>
          </li>
            <li>
              <%= link_to "Logout " + current_user.email, session_path(session), method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to "Sign Up", root_path %>
            </li>
            <li>
              <a data-toggle="modal" data-target="#signinModal" data-remote="<%= new_session_path(current_user) %> #new_session_modal">Sign In</a>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  

    <div ng-show="errors" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" ng-click="clearErrors();" aria-hidden="true">&times;</button>
      <ul>
        <li ng-repeat="(attribute, error) in errors">
          {{attribute}} {{error.join(", ")}}
        </li>
      </ul>
    </div>

    <div class="tab-content" x-ng-controller="LeagueCtrl" x-ng-init="setLeague(<%= @league.id %>);">
      <div class="tab-pane active" id="home">
        <div ui-view></div>
      </div>
    </div>

</div>

<div class="modal fade" id="signinModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
    </div>
  </div>
</div>
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>