config/routes.rb
LeagueApp::Application.routes.draw do

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  resources :sessions
  resources :leagues do
    get 'allLeagues', on: :collection
  end
  resources :days
  resources :games
  resources :teams do
    get 'allTeams', on: :collection
  end
  resources :users
  resources :stats
  resources :teams
  resources :players do
    get 'teamPlayers', on: :collection
  end
  resources :league_teams 
  resources :team_leagues, only: :index
  
  root 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
	require 'bcrypt'
	has_secure_password
	before_save { self.email = email.downcase }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :name, presence: true
  validates :phone, presence: true
	validates :password, length: {minimum: 6}, on: :create

  has_many :leagues
  has_many :teams
  has_many :players, through: :teams
  has_many :days, through: :leagues
  has_many :games, through: :days
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  # GET /users/1
  def index
    respond_with current_user
  end

  def show
    respond_with current_user
  end

  # GET /users/new
  def new
    if current_user && current_user.user_type == 'league_admin'
      redirect_to leagues_path
    elsif current_user && current_user.user_type == 'team_owner'
      if current_user.teams.count > 0
        redirect_to current_user.teams.first
      else
        redirect_to new_team_path
      end
    end
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      session[:remember_token] = @user.id
      if @user.user_type == "league_admin"
        redirect_to leagues_path, notice: 'User was successfully created.'
      else
        redirect_to new_team_path, notice: 'User was successfully created.'
      end
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email, :phone, :user_type, :password, :password_confirmation)
    end
end

app/views/users/_form.html.erb
<div class="col-sm-8 col-sm-offset-2">
  <%= form_for @user, class: 'form-horizontal' do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited you from creating an account:</h2>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li style="color:white"><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
</div>

<div class="col-sm-4 col-sm-offset-2" id="team_signup">
  <h2>Search for Teams</h2>
    <center>
    <input type="text" class="form-control" ng-model="teamSearch" placeholder="Search for Teams on RecStar">
    <accordion close-others="true" >
      <accordion-group x-ng-repeat="team in teams | filter:teamSearch" x-ng-if="teamSearch" style="margin-top:0px;">
        <accordion-heading>
          <h4 style="margin: 0 auto 0 auto;">{{team.name}}</h4>
        </accordion-heading>
        <div>
          <h5><i>Coach:</i><strong> {{team.coach}} </strong></h5>
          <h5><i>Home City:</i><strong> {{team.home_city}} </strong></h5>
          <h5><i>Mascot:</i><strong> {{team.mascot}} </strong></h5>
          <a href="/teams/{{team.id}}" class="btn btn-primary">Team Site</a>
        </div>
      </accordion-group>
    </accordion>
  </center>
  <hr>
  <h2>Run a Team</h2>
  <p style="color:#ccc">Fill out this form if you would like to create a team and find leagues to join in your area.</p>
  <%= form_for @user, class: 'form-horizontal'  do |f| %>
    <div class="actions">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %><br>
      <%= f.text_field :email, class: 'form-control', placeholder: 'Email' %><br>
      <%= f.phone_field :phone, class: 'form-control', placeholder: 'Phone' %><br>
      <%= f.password_field :password, class: 'form-control', placeholder: 'Password (minimum 6 characters)'%><br>
      <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirm Password'%>
      <%= f.hidden_field :user_type, class: 'form-control', value: "team_owner" %><br>
      <span><%= f.submit "Sign Up", class: "btn btn-info" %></span>
    </div>
  <% end %>
</div>

<div class="col-sm-4" id="league_signup">
  
  <h2  style="text-align:right">Search for Leagues</h2>
    <center>
    <input type="text" class="form-control" ng-model="leagueSearch" placeholder="Search for Leagues on RecStar">
    <accordion close-others="true" >
      <accordion-group x-ng-repeat="league in leagues | filter:leagueSearch" x-ng-if="leagueSearch" style="margin-top:0px;">
        <accordion-heading>
          <h4 style="margin: 0 auto 0 auto;">{{league.name}}</h4>
        </accordion-heading>
        <div>
          <h5><i>Start Date:</i><strong> {{league.start_date | date:('fullDate')}} </strong></h5>
          <h5><i>End Date:</i><strong> {{league.end_date | date:('fullDate')}} </strong></h5>
          <h5><i>Sport:</i><strong> {{league.sport}} </strong></h5>
          <h5><i>Locations:</i><strong> {{league.locations}}</strong></h5>
          <h5><i>Description:</i><strong> {{league.description}}</strong></h5>
          <a href="/leagues/{{league.id}}" class="btn btn-primary">League Site</a>
        </div>
      </accordion-group>
    </accordion>
  </center>
  <hr>
  <h2 style="text-align:right">Run Leagues</h2>
  <p style="color:#ccc;text-align:right">Fill out this form if you would like to create leagues for teams in your area to find and join.</p>
  <%= form_for @user, class: 'form-horizontal'  do |f| %>
    <div class="actions">
      <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %><br>
      <%= f.text_field :email, class: 'form-control', placeholder: 'Email' %><br>
      <%= f.phone_field :phone, class: 'form-control', placeholder: 'Phone' %><br>
      <%= f.password_field :password, class: 'form-control', placeholder: 'Password (minimum 6 characters)'%><br>
      <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirm Password'%>
      <%= f.hidden_field :user_type, class: 'form-control', value: "league_admin" %><br>
      <span style="float:right"><%= f.submit "Sign Up", class: "btn btn-info" %></span>
    </div>
  <% end %>
  <br>
  <br>
  <br>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-4"></div>
		<div class="col-sm-4">
			<center>
				<h1>( RecStar )</h1>
				<% if current_user %>
					<%= link_to "Logout ", session_path(session), method: :delete %>
				<% else %>
					<a data-toggle="modal" class="btn btn-default btn-lrg btn-block" style="width:50%" data-target="#signinModal" data-remote="<%= new_session_path(current_user) %> #new_session_modal">Sign In</a>
				<% end %>
			</center>
		</div>
	</div>
	<div class="row" x-ng-app="visitorApp" x-ng-controller="VisitorsCtrl">
		<%= render 'form' %>
	</div>
</div>

<div class="modal fade" id="signinModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
    </div>
  </div>
</div>

		           